apiVersion: batch/v1
kind: Job
metadata:
  name: ml-container
  namespace: pedrobeltrao
spec:
  template:
    metadata:
      labels:
        app: ml-container
    spec:
      containers:
      - name: ml-container
        image: pedrosantiago7/ml-container:03
        volumeMounts:
        - name: data-volume
          mountPath: /mnt/data
        env:
        - name: DATASET_PATH
          valueFrom:
            configMapKeyRef:
              name: dataset-config
              key: dataset_path
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: project2-pv2-pedrobeltrao-claim
  backoffLimit: 1