apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-pedrobeltrao-claim
  namespace: pedrobeltrao
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: pedrobeltrao
  storageClassName: default-storage-class-pedrobeltrao